//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Cities')
export class CitiesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  CityID: string;

  @Column('text', { nullable: true })
  CityName: string;

  @Column('text', { nullable: true })
  RegionOrProvince: string;
}
