//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Menus')
export class MenusEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  ItemName: string;

  @Column('text', { nullable: true })
  Description: string;

  @Column('real', { nullable: true })
  Price: number;

  @Column('text', { nullable: true })
  Category: string;

  @Column('text', { nullable: true })
  Availability: string;
}
