//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Restaurants')
export class RestaurantsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  Name: string;

  @Column('integer', { nullable: true })
  City: number;

  @Column('text', { nullable: true })
  Address: string;

  @Column('integer', { nullable: true })
  MenuItems: number;

  @Column('real', { nullable: true })
  Ratings: number;

  @Column('text', { nullable: true })
  ContactInformation: string;
}
