//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const RestaurantsTitle = () => {
  const record = useRecordContext();
  return <span>Restaurants {record ? `"${record.Name}"` : ''}</span>;
};

export const RestaurantsList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <TextField source="Name" />
      <ReferenceField source="City" reference="Cities" />
      <TextField source="Address" />
      <ReferenceField source="MenuItems" reference="Menus" />
      <NumberField source="Ratings" />
      <TextField source="ContactInformation" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const RestaurantsEdit = () => (
  <Edit title={<RestaurantsTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="Name" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="City" reference="Cities" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Address" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="MenuItems" reference="Menus" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="Ratings" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="ContactInformation" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const RestaurantsCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="Name" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="City" reference="Cities" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Address" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="MenuItems" reference="Menus" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="Ratings" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="ContactInformation" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  <ReferenceInput source="City" label="City" reference="Cities" alwaysOn />,
  ,
  <ReferenceInput
    source="MenuItems"
    label="MenuItems"
    reference="Menus"
    alwaysOn
  />,
  ,
  ,
];
