//Source code generated by AppGPT (www.appgpt.tech)
import { Admin, Resource, CustomRoutes } from 'react-admin';
import { customDataProvider } from './dataProvider';
import fakeDataProvider from 'ra-data-fakerest';
import { Dashboard } from './dashboard';
import { authProvider, apInitialize } from './authProvider';
import { i18nProvider } from './i18nProvider';
import LoginPage, { Login } from './Login';
import data from './data';
import {
  RestaurantsList,
  RestaurantsCreate,
  RestaurantsEdit,
} from './resources/Restaurants';
import { MenusList, MenusCreate, MenusEdit } from './resources/Menus';
import { OrdersList, OrdersCreate, OrdersEdit } from './resources/Orders';
import { UsersList, UsersCreate, UsersEdit } from './resources/Users';
import { CitiesList, CitiesCreate, CitiesEdit } from './resources/Cities';
import RestaurantsIcon from '@mui/icons-material/RestaurantMenu';
import MenusIcon from '@mui/icons-material/MenuBook';
import OrdersIcon from '@mui/icons-material/ShoppingCart';
import UsersIcon from '@mui/icons-material/Person';
import CitiesIcon from '@mui/icons-material/LocationCity';
// SUPERTOKENS
import React from 'react';
import SuperTokens, {
  SuperTokensWrapper,
  getSuperTokensRoutesForReactRouterDom,
} from 'supertokens-auth-react';
import ThirdPartyPasswordless from 'supertokens-auth-react/recipe/thirdpartypasswordless';
import Session from 'supertokens-auth-react/recipe/session';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import * as reactRouterDom from 'react-router-dom';
let sessionFn = Session.init();
SuperTokens.init({
  appInfo: {
    appName: import.meta.env.VITE_SUPERTOKENS_APPNAME,
    apiDomain: import.meta.env.VITE_BACKEND_DOMAIN,
    websiteDomain: import.meta.env.VITE_SUPERTOKENS_WEBSITEDOMAIN,
    apiBasePath: import.meta.env.VITE_BACKEND_APIPATH + '/auth',
    websiteBasePath: import.meta.env.VITE_SUPERTOKENS_WEBSITEBASEPATH,
  },
  recipeList: [
    ThirdPartyPasswordless.init({
      contactMethod: 'EMAIL',
      signInUpFeature: {
        providers: [
          ThirdPartyPasswordless.Github.init(),
          //ThirdPartyPasswordless.Google.init(),
          //ThirdPartyPasswordless.Facebook.init(),
          //ThirdPartyPasswordless.Apple.init(),
        ],
      },
    }),
    sessionFn,
  ],
});
apInitialize(Session);
// END SUPERTOKENS
let dataProvider: any;
if (import.meta.env.VITE_USE_BACKEND_DATA === 'true') {
  dataProvider = customDataProvider(
    import.meta.env.VITE_BACKEND_DOMAIN +
      import.meta.env.VITE_BACKEND_APIPATH +
      '/proxy',
  );
} else {
  dataProvider = fakeDataProvider(data.defaultData);
}

const App = () => (
  <SuperTokensWrapper>
    <BrowserRouter basename="/a256f7c97">
      <Admin
        authProvider={
          import.meta.env.VITE_ENVIRONMENT != 'DEV' ? authProvider : undefined
        }
        requireAuth
        loginPage={LoginPage}
        dataProvider={dataProvider}
        i18nProvider={i18nProvider}
        dashboard={Dashboard}
      >
        <Resource
          name="Restaurants"
          options={{ label: 'Restaurants' }}
          list={RestaurantsList}
          create={RestaurantsCreate}
          edit={RestaurantsEdit}
          recordRepresentation="Name"
          icon={RestaurantsIcon}
        />
        <Resource
          name="Menus"
          options={{ label: 'Menus' }}
          list={MenusList}
          create={MenusCreate}
          edit={MenusEdit}
          recordRepresentation="ItemName"
          icon={MenusIcon}
        />
        <Resource
          name="Orders"
          options={{ label: 'Orders' }}
          list={OrdersList}
          create={OrdersCreate}
          edit={OrdersEdit}
          recordRepresentation="OrderID"
          icon={OrdersIcon}
        />
        <Resource
          name="Users"
          options={{ label: 'Users' }}
          list={UsersList}
          create={UsersCreate}
          edit={UsersEdit}
          recordRepresentation="Name"
          icon={UsersIcon}
        />
        <Resource
          name="Cities"
          options={{ label: 'Cities' }}
          list={CitiesList}
          create={CitiesCreate}
          edit={CitiesEdit}
          recordRepresentation="CityName"
          icon={CitiesIcon}
        />
        <CustomRoutes noLayout>
          {/*This renders the login UI on the /auth route*/}
          {getSuperTokensRoutesForReactRouterDom(reactRouterDom)}
          {/*Your app routes*/}
        </CustomRoutes>
      </Admin>
    </BrowserRouter>
  </SuperTokensWrapper>
);

export default App;
